[tool.poetry]
name = "chatboot-langchain"
version = "0.1.0"
description = ""
authors = ["pedro.rodrigues <pedrook16@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
